### ISSUE TITLE
Bug In Run Algorithm command

### ISSUE THREAD

**Issue by Ojvar** [Ojvar/ExchangePrediction#95]
User @Mahdi-Dzh 

After run **pa migrate**
Then, run commands :

cd ./PythonCodes/Algorithms
source bin/activate
python main.py

I faced with below error:

Update Trades
All Algorithms started
---------------------------------------
Traceback (most recent call last):
  File "/var/www/amax.io/PythonCodes/Algorithms/lib/python3.7/site-packages/mysql/connector/cursor.py", line 559, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/var/www/amax.io/PythonCodes/Algorithms/lib/python3.7/site-packages/mysql/connector/connection.py", line 498, in cmd_query
    'Use cmd_query_iter for statements with multiple queries.')
mysql.connector.errors.InterfaceError: Use cmd_query_iter for statements with multiple queries.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 85, in <module>
    main ();
  File "main.py", line 41, in main
    companies = base.loadCompaniesForAlgorithms ();
  File "/var/www/amax.io/PythonCodes/Algorithms/classes/algorithm_base.py", line 378, in loadCompaniesForAlgorithms
    self.mycursor.execute (sql);
  File "/var/www/amax.io/PythonCodes/Algorithms/lib/python3.7/site-packages/mysql/connector/cursor.py", line 563, in execute
    "Use multi=True when executing multiple statements")
mysql.connector.errors.InterfaceError: Use multi=True when executing multiple statements

**Comment by Mahdi-Dzh** [comment]
I fixed it on server.
